import { Info, X, TrendingUp, TrendingDown, Minus } from "lucide-react";

function FactorTrend({ factor }) {
  if (factor.currentValue == null) return null;
  const Icon = factor.trend === "up" ? TrendingUp : factor.trend === "down" ? TrendingDown : Minus;
  const tone =
    factor.trend === "up"
      ? "text-emerald-600 dark:text-emerald-400"
      : factor.trend === "down"
      ? "text-red-600 dark:text-red-400"
      : "text-rice-500 dark:text-rice-400";
  return (
    <span className={`flex shrink-0 items-center gap-1 text-xs font-semibold ${tone}`}>
      <Icon className="h-3 w-3" />
      {factor.currentValue.toFixed(factor.decimals ?? 2)} {factor.unit}
    </span>
  );
}

export default function ModelInfoPanel({ open, onClose, info, horizon }) {
  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-4 sm:items-center"
      onClick={onClose}
    >
      <div
        className="max-h-[85vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-xl dark:bg-rice-900"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="mb-4 flex items-center justify-between">
          <h3 className="flex items-center gap-2 text-base font-bold text-rice-900 dark:text-white">
            <Info className="h-5 w-5 text-rice-700 dark:text-rice-300" />
            How this forecast was made
          </h3>
          <button onClick={onClose} className="rounded-full p-1 hover:bg-rice-50 dark:hover:bg-white/10">
            <X className="h-5 w-5 text-rice-700 dark:text-rice-300" />
          </button>
        </div>

        <p className="mb-4 text-sm text-rice-900/80 dark:text-rice-100/80">
          Forecast is generated by <strong>P-RICE</strong>, an XGBoost regression model trained
          on historical rice prices and market indicators (Brent oil, farmgate price, inflation,
          rice stocks, exchange rate, temperature, rainfall, and volume of production). This card shows the model's most recent{" "}
          <strong>{horizon}-month-ahead</strong> forecast from the held-out test set, compared
          against ARIMA and a naive "same as last month" baseline.
        </p>

        {info?.decision && (
          <div className="mb-4 rounded-xl bg-rice-50 p-4 dark:bg-white/5">
            <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-rice-700 dark:text-rice-300">
              Mean Absolute Error at {horizon} month{horizon > 1 ? "s" : ""} ahead
            </p>
            <div className="grid grid-cols-3 gap-2 text-center text-sm">
              <div>
                <p className="font-bold text-rice-900 dark:text-white">{info.decision.xgboost?.toFixed(3)}</p>
                <p className="text-xs text-rice-700 dark:text-rice-300">XGBoost</p>
              </div>
              <div>
                <p className="font-bold text-rice-900 dark:text-white">{info.decision.arima?.toFixed(3)}</p>
                <p className="text-xs text-rice-700 dark:text-rice-300">ARIMA</p>
              </div>
              <div>
                <p className="font-bold text-rice-900 dark:text-white">{info.decision.naive?.toFixed(3)}</p>
                <p className="text-xs text-rice-700 dark:text-rice-300">Naive</p>
              </div>
            </div>
            <p className="mt-2 text-xs text-rice-700 dark:text-rice-300">
              {info.decision.beatsArima && info.decision.beatsNaive
                ? "XGBoost beats both benchmarks at this horizon."
                : "XGBoost does not beat both benchmarks at this horizon — check the Horizon Decision sheet."}
            </p>
          </div>
        )}

        {info?.topFactors?.length > 0 && (
          <div>
            <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-rice-700 dark:text-rice-300">
              Top factors driving this forecast (SHAP)
            </p>
            <div className="space-y-2.5">
              {info.topFactors.map((f) => {
                const max = info.topFactors[0].meanAbsShap || 1;
                const pct = Math.max(6, (f.meanAbsShap / max) * 100);
                return (
                  <div key={f.factor}>
                    <div className="flex items-center justify-between gap-2">
                      <span className="truncate text-xs text-rice-900 dark:text-rice-100">
                        {f.label || f.factor}
                      </span>
                      <FactorTrend factor={f} />
                    </div>
                    <div className="mt-1 h-2 rounded-full bg-rice-50 dark:bg-white/10">
                      <div
                        className="h-2 rounded-full bg-rice-600 dark:bg-rice-400"
                        style={{ width: `${pct}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
            <p className="mt-2 text-[11px] text-rice-900/50 dark:text-rice-100/50">
              Bar length = relative importance (mean |SHAP|). Values shown are the most recent
              monthly reading, with the trend arrow comparing it to the prior month.
            </p>
          </div>
        )}

        <p className="mt-5 text-[11px] leading-relaxed text-rice-900/50 dark:text-rice-100/50">
          Note: this is a backtested forecast — the target month falls inside the historical
          dataset used to evaluate the model, not beyond it. It shows how P-RICE would have
          performed on unseen data, using the same walk-forward setup described in Chapter 3.
        </p>
      </div>
    </div>
  );
}
